name: Create Distribution

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  create-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: zip -r ZahCorp-Client.zip * -x .github/*
      - name: Publish Release
        uses: meeDamian/github-release@v2.0.3
        with:
          token: ${{ secrets.RELEASE_SECRET }}
          tag: ${{ steps.get_tag_name.outputs.VERSION }}
          prerelease: false
          gzip: false
          files: ZahCorp-Client.zip
          allow_override: true
      - name: Push to CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          project_id: ${{ secrets.PROJECT_ID }}
          game_endpoint: minecraft
          file_path: ZahCorp-Client.zip
          game_versions: minecraft-1.12.2
          release_type: alpha
